apiVersion: v1
kind: Service
metadata:
  name: online-shop-v1
  namespace: canary-deployment
spec:
  selector:
    app: online-shop
    version: v1
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: online-shop-v2
  namespace: canary-deployment
spec:
  selector:
    app: online-shop
    version: v2
  ports:
    - port: 80
      targetPort: 3000
